
services:
  nginx:
    build: services/nginx
    image: nginx:jesus
    container_name: nginx
    ports:
      - 443:443
    expose:
      - 443
    depends_on:
      - wordpress
    volumes:
      - wp:/var/www/wordpress
    networks:
      - my_network
    restart: always

  wordpress:
    build: services/wordpress
    image: wordpress:jesus
    container_name: wordpress
    expose:
      - 9000
    depends_on:
      - mariadb
    env_file: .env
    volumes:
      - wp:/var/www/wordpress
    networks:
      - my_network
    restart: always

  mariadb:
    build: services/mariadb
    image: mariadb:jesus
    container_name: mariadb
    expose:
      - 3306
    env_file: .env
    networks:
      - my_network
    volumes:
      - db:/var/lib/mysql
    restart: always

networks:
  my_network:


volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/kali/data/wp

  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/kali/data/db
